services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    # ---- Build configuration ----
    buildFilter:
      paths:
        - "**"
      ignoredPaths:
        - "node_modules/**"
        - "vendor/**"
        - "storage/logs/**"
        - ".git/**"

    # ---- Runtime environment variables ----
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://commenting-system-task.onrender.com
      - key: PORT
        value: 8000
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug

      # --- SQLite by default ---
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
      - key: DB_FOREIGN_KEYS
        value: true

      # --- Session and cache configuration ---
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_LIFETIME
        value: 120
      - key: VIEW_COMPILED_PATH
        value: /tmp
      - key: CACHE_PREFIX
        value: laravel_cache

      # --- Uncomment & edit for MySQL/Postgres instead ---
      # - key: DB_CONNECTION
      #   value: mysql
      # - key: DB_HOST
      #   fromDatabase:
      #     name: laravel-mysql
      #     property: host
      # - key: DB_PORT
      #   fromDatabase:
      #     name: laravel-mysql
      #     property: port
      # - key: DB_DATABASE
      #   fromDatabase:
      #     name: laravel-mysql
      #     property: database
      # - key: DB_USERNAME
      #   fromDatabase:
      #     name: laravel-mysql
      #     property: user
      # - key: DB_PASSWORD
      #   fromDatabase:
      #     name: laravel-mysql
      #     property: password

    # ---- Persistent storage for SQLite ----
    disks:
      - name: data
        mountPath: /var/data
        sizeGB: 1

    # ---- Health check ----
    healthCheckPath: /

    # ---- Resource limits ----
    plan: free

    # ---- Build optimization for free tier ----
    buildCommand: echo "Using Dockerfile build"
