services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile      # path relative to repo root
    autoDeploy: true

    # ---- Runtime environment variables ----
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://commenting-system-task.onrender.com

      # --- SQLite by default ---
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite

      # --- Uncomment & edit for MySQL/Postgres instead ---
      # - key: DB_CONNECTION
      #   value: mysql
      # - key: DB_HOST
      #   fromDatabase:
      #     name: laravel-mysql
      #     property: host
      # - key: DB_PORT
      #   fromDatabase:
      #     name: laravel-mysql
      #     property: port
      # - key: DB_DATABASE
      #   fromDatabase:
      #     name: laravel-mysql
      #     property: database
      # - key: DB_USERNAME
      #   fromDatabase:
      #     name: laravel-mysql
      #     property: user
      # - key: DB_PASSWORD
      #   fromDatabase:
      #     name: laravel-mysql
      #     property: password

    # ---- Persistent storage for SQLite ----
    disks:
      - name: data
        mountPath: /var/data    # must match DB_DATABASE path
        sizeGB: 1
